import localFont from 'next/font/local'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const anderson = localFont({
  src: [
    {
      path: '../public/fonts/AndersonGrotesk-Bold.otf',
      weight: '700',
    }
  ],
  variable: '--font-anderson',

})

const clash = localFont({
  src: '../public/fonts/ClashDisplay-Variable.ttf',
  variable: '--font-clash'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anderson.variable} font-anderson ${clash.variable}`}>{children}</body>
    </html>
  );
}
